export const QUERY_KEY = {
    GET_BEST_SELLER_PRODUCTS: "GET_BEST_SELLER_PRODUCTS",
    GET_ACTIVE_PRODUCTS: "GET_ACTIVE_PRODUCTS",
    GET_PRODUCT_BY_ID: "GET_PRODUCT_BY_ID",
    GET_UPCOMING_CAMPAIGNS: "GET_UPCOMING_CAMPAIGNS",
    GET_CAMPAIGN_BY_ID: "GET_CAMPAIGN_BY_ID",
    GET_FEATURED_PRODUCTS_BY_TYPE: "GET_FEATURED_PRODUCTS_BY_TYPE",
    GET_PRODUCTS_LIST: "GET_PRODUCTS_LIST",
    GET_ACTIVE_PROMOTIONS: "GET_ACTIVE_PROMOTIONS",
    GET_USER_PROMOTIONS: "GET_USER_PROMOTIONS",
    GET_CUSTOMER_ACCOUNT_SUMMARY: "GET_CUSTOMER_ACCOUNT_SUMMARY",
    GET_USER_WISHLIST: "GET_USER_WISHLIST",
    IS_PRODUCT_FAVORITED: "IS_PRODUCT_FAVORITED",
    GET_CUSTOMER_ORDER_HISTORY: "GET_CUSTOMER_ORDER_HISTORY",
    GET_CUSTOMER_ORDER_DETAIL: "GET_CUSTOMER_ORDER_DETAIL"
};
